# Dynamic programming

Describe the contents

In [4]:
import numpy as np

In [ ]:
# Initial values
v_s = ['states', 'actions', 'rewards']
iterations = 10

# Experiment
for t in range(iterations):
    states, actions, rewards = play_game(policy)
    v_s = [states, actions, rewards]

## Gridworld in code

Explain that we are going to create a grid world.

In [84]:
class Gridworld:
    def __init__(self, rows, cols, start) -> None:
        grids = np.zeros((rows, cols))
        grids[start[0]][start[1]] = 1
        self.board = grids
        self.state = (start[0], start[1])
        self.game_data = self._new_data(rows, cols)
        self.terminal_states = list()

    def _new_data(self, rows, cols):
        """
        Method to generate the new game data
        """
        reward = 0
        action = list('udrl')
        data = dict()
        for row in range(rows):
            for col in range(cols):
                data[(row, col)] = [reward, action]
        return data


    def set(self, rewards, actions):
        for k, r in rewards.items():
            self.game_data[k][0] = r
        for k, a in actions.items():
            self.game_data[k][1] = list(a)

    def game_over(self) -> bool:
        return self.state in self.terminal_states

    def policy(self, state):
        return 'r'

    def move(self, action):
        if action in self.game_data[self.state][1]:
            self.state = list(self.state)
            if action == 'u':
                self.state[0] -= 1
            elif action == 'd':
                self.state[0] += 1
            elif action == 'r':
                self.state[1] += 1
            elif action == 'l':
                self.state[1] -= 1
        self._trace()
        self.state = tuple(self.state)
        return self.game_data[self.state][0]

    def _trace(self):
        self.board[self.state[0]][self.state[1]] = 1

    def render(self):
        print(self.board)

In [85]:
# Setting up the game
g = Gridworld(3, 4, (2, 0))
g.set(
    rewards= {(0, 3): 1, (1, 3): -1},
    actions = {
        (0, 0): 'rd',
        (0, 1): 'rl',
        (0, 2): 'rld',
        (0, 3): '',
        (1, 0): 'ud',
        (1, 1): '',
        (1, 2): 'udr',
        (1, 3): '',
        (2, 0): 'ur',
        (2, 1): 'rl',
        (2, 2): 'rlu',
        (2, 3): 'lu',
        }
    )

In [86]:
# Play the game
while not g.game_over():
    s = g.state
    a = g.policy(s)
    r = g.move(a)
    g.render()
    print('----------')

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 0. 0.]]
----------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 0.]]
----------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]]
----------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]]
----------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]]
----------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]]
----------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]]
----------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]]
----------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]]
----------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]]
----------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]]
----------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]]
----------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]]
----------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]]
----------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]]
----------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]]
----------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]]
----------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 

KeyboardInterrupt: 